"""Web API 的 HTTP 契约与后续路由入口。"""

from app.web.contracts import (
    API_SESSIONS_PATH,
    API_COMMAND_APPROVAL_DECISION_PATH,
    API_SESSION_PATH,
    API_SESSION_TASKS_PATH,
    API_TASK_CANCEL_PATH,
    API_TASK_COMMAND_APPROVALS_PATH,
    API_TASK_MESSAGES_PATH,
    API_TASK_STEPS_PATH,
    API_TASK_TOOL_CALLS_PATH,
    API_TASK_PATH,
    API_TASK_SNAPSHOT_PATH,
    AgentStepResponse,
    CancelTaskResponse,
    CommandApprovalDecisionRequest,
    CommandApprovalResponse,
    CreateSessionRequest,
    CreateSessionResponse,
    CreateSessionTaskRequest,
    CreateSessionTaskResponse,
    ErrorResponse,
    MessageResponse,
    SessionSummaryResponse,
    TaskSnapshotResponse,
    TaskResponse,
    ToolCallResponse,
)
from app.web.query_service import ConversationQueryService, TaskQueryService

__all__ = [
    "API_SESSIONS_PATH",
    "API_COMMAND_APPROVAL_DECISION_PATH",
    "API_SESSION_PATH",
    "API_SESSION_TASKS_PATH",
    "API_TASK_CANCEL_PATH",
    "API_TASK_COMMAND_APPROVALS_PATH",
    "API_TASK_MESSAGES_PATH",
    "API_TASK_STEPS_PATH",
    "API_TASK_TOOL_CALLS_PATH",
    "API_TASK_PATH",
    "API_TASK_SNAPSHOT_PATH",
    "AgentStepResponse",
    "CancelTaskResponse",
    "CommandApprovalDecisionRequest",
    "CommandApprovalResponse",
    "CreateSessionRequest",
    "CreateSessionResponse",
    "CreateSessionTaskRequest",
    "CreateSessionTaskResponse",
    "ConversationQueryService",
    "ErrorResponse",
    "MessageResponse",
    "SessionSummaryResponse",
    "TaskSnapshotResponse",
    "TaskResponse",
    "TaskQueryService",
    "ToolCallResponse",
]
