"""本地工具定义与执行模块。"""

from app.tools.contracts import (
    DEFAULT_READ_ONLY_FILE_TOOL_LIMITS,
    DEFAULT_TOOL_PATH,
    FileEntryType,
    ListedFile,
    ListFilesArguments,
    ReadFileArguments,
    ReadOnlyFileToolLimits,
    SearchFilesArguments,
    SearchMatch,
    UnsupportedTextFileError,
    decode_utf8_text,
    format_list_files_result,
    format_search_files_result,
)
from app.tools.file_tools import (
    FileToolArguments,
    FileToolResourceLimitError,
    ListFilesTool,
    ReadFileTool,
    ReadOnlyFileTool,
    SearchFilesTool,
)
from app.tools.path_guard import (
    WorkspacePathConfigurationError,
    WorkspacePathError,
    WorkspacePathGuard,
    WorkspacePathNotFoundError,
    WorkspacePathRejectedError,
    WorkspacePathTypeError,
)
from app.tools.registry import (
    DuplicateFileToolError,
    FileToolNotFoundError,
    FileToolRegistry,
    FileToolRegistryError,
    create_read_only_file_tool_registry,
)
from app.tools.router import PreparedToolCall, PrepareToolResult, ToolRouter
from app.tools.schemas import (
    LIST_FILES_SCHEMA,
    READ_FILE_SCHEMA,
    READ_ONLY_FILE_TOOL_SCHEMAS,
    SEARCH_FILES_SCHEMA,
)

__all__ = [
    "DEFAULT_READ_ONLY_FILE_TOOL_LIMITS",
    "DEFAULT_TOOL_PATH",
    "FileEntryType",
    "ListedFile",
    "ListFilesArguments",
    "ReadFileArguments",
    "ReadOnlyFileToolLimits",
    "SearchFilesArguments",
    "SearchMatch",
    "UnsupportedTextFileError",
    "decode_utf8_text",
    "format_list_files_result",
    "format_search_files_result",
    "LIST_FILES_SCHEMA",
    "READ_FILE_SCHEMA",
    "READ_ONLY_FILE_TOOL_SCHEMAS",
    "SEARCH_FILES_SCHEMA",
    "WorkspacePathConfigurationError",
    "WorkspacePathError",
    "WorkspacePathGuard",
    "WorkspacePathNotFoundError",
    "WorkspacePathRejectedError",
    "WorkspacePathTypeError",
    "FileToolArguments",
    "FileToolResourceLimitError",
    "ListFilesTool",
    "ReadFileTool",
    "ReadOnlyFileTool",
    "SearchFilesTool",
    "DuplicateFileToolError",
    "FileToolNotFoundError",
    "FileToolRegistry",
    "FileToolRegistryError",
    "create_read_only_file_tool_registry",
    "PreparedToolCall",
    "PrepareToolResult",
    "ToolRouter",
]
